config/routes.rb
Rails.application.routes.draw do
  resources :cats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'cats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cat.rb
# frozen_string_literal: true

class Cat
  delegate :id, :name, :breed, :favorite_quote, :created_at, to: :@record

  def initialize(record)
    @record = record
  end
end

app/models/cat/create.rb
# frozen_string_literal: true

class Cat
  class Create < ::Micro::Case
    include ActiveModel::Validations

    attribute :name
    attribute :breed
    attribute :favorite_quote
    attribute :repository, default: Repository

    validates :name, :breed, :favorite_quote, presence: true

    def call!
      return Failure(:invalid_params, result: { errors: self.errors }) unless valid?

      cat = repository.create_cat(name, breed, favorite_quote)

      Success(result: { cat: })
    end
  end
end

app/models/cat/destroy.rb
# frozen_string_literal: true

class Cat
  class Destroy < ::Micro::Case
    include ActiveModel::Validations

    attribute :id
    attribute :repository, default: Repository

    def call!
      repository.destroy_cat(id)

      Success()
    rescue ActiveRecord::RecordNotFound
      Failure(:not_found)
    end
  end
end

app/models/cat/filter.rb
# frozen_string_literal: true

class Cat
  class Filter < ::Micro::Case
    attribute :repository, default: Repository

    def call!
      cats = repository.filter_cats

      Success(result: { cats: })
    end
  end
end

app/models/cat/find.rb
# frozen_string_literal: true

class Cat
  class Find < ::Micro::Case
    attribute :id
    attribute :repository, default: Repository

    def call!
      cat = repository.find_cat(id)

      return Failure(:not_found) unless cat

      Success(result: { cat: })
    end
  end
end

app/models/cat/record.rb
# frozen_string_literal: true

class Cat
  class Record < ApplicationRecord
    self.table_name = 'cats'
  end
end

app/models/cat/repository.rb
# frozen_string_literal: true

class Cat
  module Repository
    module_function

    ToCat = ->(record) { ::Cat.new(record) }
    private_constant :ToCat

    def filter_cats
      Record
        .select(:id, :name, :breed, :favorite_quote, :created_at)
        .order(created_at: :desc)
        .map(&ToCat)
    end

    def find_cat(id)
      Record
        .select(:id, :name, :breed, :favorite_quote)
        .find_by(id: id)
        &.then(&ToCat)
    end

    def create_cat(name, breed, favorite_quote)
      Record
        .create(name: name, breed: breed, favorite_quote: favorite_quote)
        .then(&ToCat)
    end

    def update_cat(id, name, breed, favorite_quote)
      Record
        .update(id, name: name, breed: breed, favorite_quote: favorite_quote)
        .then(&ToCat)
    end

    def destroy_cat(id)
      Record.destroy(id)
    end

    def cat_exists?(id)
      Record.exists?(id)
    end
  end
end

app/models/cat/update.rb
# frozen_string_literal: true

class Cat
  class Update < ::Micro::Case
    include ActiveModel::Validations

    attribute :id
    attribute :name
    attribute :breed
    attribute :favorite_quote
    attribute :repository, default: Repository

    validates :name, :breed, :favorite_quote, presence: true

    def call!
      return Failure(:not_found) unless repository.cat_exists?(id)

      return Failure(:invalid_params, result: { errors: self.errors }) unless valid?

      cat = repository.update_cat(id, name, breed, favorite_quote)

      Success(result: { cat:})
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cat/form.rb
# frozen_string_literal: true

class Cat
  class Form
    attr_reader :name, :breed, :favorite_quote

    def initialize(params = {})
      @name = params[:name]
      @breed = params[:breed]
      @favorite_quote = params[:favorite_quote]
    end
  end
end

app/controllers/cats_controller.rb
# frozen_string_literal: true

class CatsController < ApplicationController
  def index
    result = Cat::Filter.call

    render('cats/index', locals: { cats: result[:cats] })
  end

  def new
    render('cats/new', locals: { cat: Cat::Form.new, errors: nil })
  end

  def show
    Cat::Find.call(id: params[:id])
      .on_success { |result| render('cats/show', locals: { cat: result[:cat] }) }
      .on_failure(:not_found) { redirect_to(cats_path, notice: 'Cat not found!') }
  end

  def edit
    Cat::Find.call(id: params[:id])
      .on_success { |result| render('cats/edit', locals: { cat: result[:cat], errors: nil }) }
      .on_failure(:not_found) { redirect_to(cats_path, notice: 'Cat not found!') }
  end

  def create
    Cat::Create.call(**cat_params)
      .on_success { |result| handle_create(result[:cat]) }
      .on_failure(:invalid_params) do |result|
        render(
          turbo_stream: turbo_stream.update('cat-errors', partial: 'cats/form/errors', locals: { errors: result[:errors]})
        )
      end
  end

  def update
    Cat::Update.call(**cat_params.merge({ id: params[:id] }))
      .on_success { |result| render('cats/show', locals: { cat: result[:cat] }, status: :see_other) }
      .on_failure(:not_found) { redirect_to(cats_path, notice: 'Cat not found!') }
      .on_failure(:invalid_params) do |result|
        render(
          turbo_stream: turbo_stream.update('cat-errors', partial: 'cats/form/errors', locals: { errors: result[:errors]})
        )
      end
  end

  def destroy
    Cat::Destroy.call(id: params[:id])
      .on_success { redirect_to(cats_path, notice: 'Cat was successfully destroyed.') }
      .on_failure(:not_found) { redirect_to(cats_path, notice: 'Cat not found!') }
  end

  private

  def cat_params
    params.require(:cat).permit(:name, :breed, :favorite_quote)
  end

  def handle_create(cat)
    Turbo::StreamsChannel.broadcast_prepend_to('cat-creation', target: 'cats', partial: 'cats/cat', locals: { cat: })
    render('cats/show', locals: { cat: }, status: :see_other)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cats/_cat.html.erb
<div id="<%= "cat_#{cat.id}" %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= cat.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Breed:</strong>
    <%= cat.breed %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Favorite quote:</strong>
    <%= cat.favorite_quote %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this cat", cat_path(cat.id), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this cat', edit_cat_path(cat.id), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/cats/_form.html.erb
<%= form_for(:cat, url: url, html: { method: method }, class: "contents") do |form| %>
  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, value: cat&.name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :breed %>
    <%= form.text_field :breed, value: cat&.breed, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :favorite_quote %>
    <%= form.text_area :favorite_quote, value: cat&.favorite_quote, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing cat</h1>

  <%= turbo_frame_tag 'cat-errors'  %>

  <%= render(
    partial: 'form',
    locals: {
      cat: cat,
      url: cat_path(cat.id),
      method: :put
    }
  ) %>

  <%= link_to "Show this cat", cat_path(cat.id), class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to cats", cats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cats/form/_errors.html.erb
<% if errors.present? %>
  <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
    <h2><%= pluralize(errors.count, "error") %> prohibited this cat from being saved:</h2>

    <ul>
      <% errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/cats/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Cats</h1>
    <%= link_to 'New cat', new_cat_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <%= turbo_stream_from 'cat-creation' %>

  <div id="cats" class="min-w-full">
    <% cats.each do |cat| %>
      <%= render(partial: 'cat', locals: { cat: cat }) %>
    <% end %>
  </div>
</div>

app/views/cats/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New cat</h1>

  <%= turbo_frame_tag 'cat-errors'  %>

  <%= render(
    partial: 'form',
    locals: {
      cat: cat,
      url: cats_path,
      method: :post
    }
  ) %>

  <%= link_to 'Back to cats', cats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cats/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render(partial: 'cat', locals: { cat: cat, action_name: 'show' }) %>

    <%= link_to 'Edit this cat', edit_cat_path(cat.id), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this cat', cat_path(cat.id), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to cats', cats_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatALog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>